# Generated by Django 2.1.5 on 2019-01-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190123_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temperature',
            old_name='celcius',
            new_name='celsius',
        ),
    ]
