# Generated by Django 2.1.5 on 2019-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190129_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('record_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='H',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rh', models.FloatField(default=0.0)),
                ('change', models.FloatField(default=0.0)),
                ('record_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Humidity',
        ),
    ]
